from app import db, app as flask_app
from artprompts.models import Prompt, Subscriber

# class Prompt(db.Model):
#     __tablename__ = 'prompt'
#     __table_args__ = {'extend_existing': True}
#     id = db.Column(db.Integer, primary_key=True)
#     text = db.Column(db.String(250), nullable=False)
#     category = db.Column(db.String(250), nullable=True)

def init_db():

    with flask_app.app_context():
        db.drop_all()
        db.create_all()
        # Insert initial prompts
        prompts = [
            ('animals', 'A cat stretching in the sun'),
            ('animals', 'A dog playing with a ball'),
            ('animals', 'A bird perched on a branch'),
            ('animals', 'A butterfly landing on a flower'),
            ('animals', 'A fish swimming in a pond'),
            ('animals', 'A lion roaring in the savannah'),
            ('animals', 'A dolphin jumping out of the water'),
            ('animals', 'A horse galloping in a field'),
            ('animals', 'A panda eating bamboo'),
            ('animals', 'A rabbit hopping through a garden'),
            ('animals', 'An owl flying through the night sky'),
            ('animals', 'A squirrel gathering nuts'),
            ('animals', 'A penguin sliding on ice'),
            ('animals', 'A peacock showing its feathers'),
            ('animals', 'A turtle slowly walking on the beach'),
            ('animals', 'A frog sitting on a lily pad'),
            ('animals', 'A snake slithering through grass'),
            ('animals', 'A deer standing in a forest'),
            ('animals', 'A koala sleeping in a tree'),
            ('animals', 'A bear catching fish from a river'),
            ('animals', 'A chameleon blending into its surroundings'),
            ('animals', 'A flamingo standing on one leg'),
            ('animals', 'A wolf howling at the moon'),
            ('animals', 'A kangaroo jumping across the outback'),
            ('animals', 'A monkey swinging from vines'),
            ('animals', 'A hedgehog curled up in a ball'),
            ('animals', 'A fox sneaking through the underbrush'),
            ('animals', 'A whale swimming in the ocean'),
            ('animals', 'A bee buzzing around a hive'),
            ('animals', 'A raccoon scavenging for food'),
            ('animals', 'A parrot talking on a pirate’s shoulder'),
            ('animals', 'A giraffe reaching for leaves in a tree'),
            ('animals', 'A cheetah sprinting across the plains'),
            ('animals', 'A starfish stuck to a rock'),
            ('animals', 'A shark gliding under the water'),
            ('animals', 'A lobster walking on the seabed'),
            ('animals', 'A seahorse floating among seaweed'),
            ('animals', 'A meerkat standing on lookout'),
            ('animals', 'A swan gliding on a lake'),
            ('animals', 'A bat hanging upside down'),
            ('animals', 'A camel walking in the desert'),
            ('animals', 'A ladybug on a leaf'),
            ('animals', 'A dragonfly hovering over a pond'),
            ('animals', 'A pelican catching fish in its beak'),
            ('animals', 'A porcupine showing its quills'),
            ('animals', 'A seal playing with a beach ball'),
            ('animals', 'A hummingbird sipping nectar'),
            ('animals', 'A jellyfish floating in the deep sea'),
            ('animals', 'A llama with a colorful saddle'),
            ('animals', 'A crocodile basking in the sun'),
            ('animals', 'A toucan in the rainforest'),
            ('animals', 'A bison grazing on the plains'),
            ('animals', 'An elephant spraying water with its trunk'),
            ('animals', 'A reindeer pulling a sleigh'),
            ('animals', 'A polar bear playing with its cub'),
            ('animals', 'A moose standing in a lake'),
            ('animals', 'A cheetah resting in the shade'),
            ('animals', 'A goat climbing a rocky hill'),
            ('animals', 'A yak in the mountains'),
            ('animals', 'A heron fishing in a stream'),
            ('animals', 'A lobster in a tide pool'),
            ('animals', 'A hamster running in a wheel'),
            ('animals', 'A goldfish in a bowl'),
            ('animals', 'A ferret exploring a tunnel'),
            ('animals', 'A guinea pig eating a carrot'),
            ('animals', 'A cockatoo with a bright crest'),
            ('animals', 'A donkey carrying a load'),
            ('animals', 'A turkey spreading its tail feathers'),
            ('animals', 'A cow grazing in a meadow'),
            ('animals', 'A pig rolling in mud'),
            ('animals', 'A sheepdog herding sheep'),
            ('animals', 'A rooster crowing at dawn'),
            ('animals', 'A sheep jumping over a fence'),
            ('animals', 'A mule standing by a barn'),
            ('animals', 'A goose honking in a pond'),
            ('animals', 'A barn owl in a barn'),
            ('animals', 'A blackbird singing on a fence'),
            ('animals', 'A robin with a red breast'),
            ('animals', 'A blue jay in a tree'),
            ('animals', 'A sparrow in a birdhouse'),
            ('animals', 'A woodpecker on a tree trunk'),
            ('animals', 'A chipmunk with full cheeks'),
            ('animals', 'A beaver building a dam'),
            ('animals', 'A stag with antlers'),
            ('animals', 'A lynx in the snow'),
            ('animals', 'A mountain goat on a cliff'),
            ('animals', 'A snow leopard in the Himalayas'),
            ('animals', 'A puffin with a fish in its beak'),
            ('animals', 'A hawk soaring in the sky'),
            ('animals', 'An eagle on a cliff edge'),
            ('animals', 'A vulture in the desert'),
            ('animals', 'A falcon diving for prey'),
            ('animals', 'An orca breaching the surface'),
            ('animals', 'A narwhal in the Arctic'),
            ('animals', 'A stingray on the ocean floor'),
            ('animals', 'A mantis shrimp with colorful claws'),
            ('animals', 'A great white shark in the deep sea'),
            ('animals', 'A pufferfish puffed up'),
            ('animals', 'An anglerfish with its lure glowing'),
            ('animals', 'A clownfish in an anemone'),
            ('still life', 'An apple in a bowl'),
            ('still life', 'A vase of sunflowers'),
            ('still life', 'A stack of old books'),
            ('still life', 'A glass of wine with grapes'),
            ('still life', 'A basket of fresh vegetables'),
            ('still life', 'A bowl of fruit with a banana, orange, and apple'),
            ('still life', 'A teapot with a cup and saucer'),
            ('still life', 'A candle beside a mirror'),
            ('still life', 'A pair of worn-out shoes'),
            ('still life', 'A wooden bowl with assorted nuts'),
            ('still life', 'A clock and a quill on a desk'),
            ('still life', 'A violin and a sheet of music'),
            ('still life', 'A pitcher of lemonade with lemons'),
            ('still life', 'A loaf of bread with a knife'),
            ('still life', 'A bouquet of roses in a glass vase'),
            ('still life', 'A bowl of cherries on a tablecloth'),
            ('still life', 'A sewing kit with needles and thread'),
            ('still life', 'A coffee mug with steam rising'),
            ('still life', 'A collection of seashells'),
            ('still life', 'A bowl of cereal with a spoon'),
            ('still life', 'A bottle of olive oil with olives'),
            ('still life', 'A plate of freshly baked cookies'),
            ('still life', 'A stack of pancakes with syrup'),
            ('still life', 'A basket of knitting yarn'),
            ('still life', 'A pair of glasses on an open book'),
            ('still life', 'A bowl of soup with a spoon'),
            ('still life', 'A pile of autumn leaves'),
            ('still life', 'A jar of honey with a dipper'),
            ('still life', 'A collection of colored pencils'),
            ('still life', 'A bowl of strawberries and cream'),
            ('still life', 'A bottle of perfume with flowers'),
            ('still life', 'A slice of cake on a plate'),
            ('still life', 'A bowl of popcorn'),
            ('still life', 'A watering can with flowers'),
            ('still life', 'A set of keys on a keyring'),
            ('still life', 'A bowl of pasta with a fork'),
            ('still life', 'A pitcher of water with ice'),
            ('still life', 'A stack of playing cards'),
            ('still life', 'A basket of apples and pears'),
            ('still life', 'A bowl of mixed berries'),
            ('still life', 'A jar of pickles'),
            ('still life', 'A bowl of oatmeal with toppings'),
            ('still life', 'A wine bottle with a corkscrew'),
            ('still life', 'A basket of fresh bread rolls'),
            ('still life', 'A pot of tea with tea bags'),
            ('still life', 'A pair of gardening gloves with tools'),
            ('still life', 'A collection of vintage postcards'),
            ('still life', 'A bowl of salad with dressing'),
            ('still life', 'A jar of spices with a spoon'),
            ('still life', 'A stack of folded towels'),
            ('still life', 'A plate of cheese and crackers'),
            ('still life', 'A bowl of ramen with chopsticks'),
            ('still life', 'A basket of Easter eggs'),
            ('still life', 'A bowl of jelly beans'),
            ('still life', 'A bowl of guacamole with chips'),
            ('still life', 'A collection of glass marbles'),
            ('still life', 'A bowl of fruit salad'),
            ('still life', 'A cup of hot chocolate with marshmallows'),
            ('still life', 'A bowl of tomato soup with bread'),
            ('still life', 'A pot of coffee with a mug'),
            ('still life', 'A jar of jam with a spoon'),
            ('still life', 'A bowl of ice cream with toppings'),
            ('still life', 'A collection of seashells and sand dollars'),
            ('still life', 'A bowl of mashed potatoes with gravy'),
            ('still life', 'A set of paintbrushes in a jar'),
            ('still life', 'A bowl of candy corn'),
            ('still life', 'A basket of fresh herbs'),
            ('still life', 'A bowl of pretzels'),
            ('still life', 'A plate of sushi rolls'),
            ('still life', 'A bowl of chili with cheese'),
            ('still life', 'A bowl of couscous with vegetables'),
            ('still life', 'A basket of fresh muffins'),
            ('still life', 'A collection of antique keys'),
            ('still life', 'A bowl of steamed vegetables'),
            ('still life', 'A set of watercolor paints'),
            ('still life', 'A bowl of clam chowder'),
            ('still life', 'A stack of magazines'),
            ('still life', 'A bowl of risotto'),
            ('still life', 'A bowl of hummus with pita bread'),
            ('still life', 'A collection of rubber stamps'),
            ('still life', 'A bowl of gazpacho'),
            ('still life', 'A set of wine glasses'),
            ('still life', 'A bowl of fruit punch'),
            ('still life', 'A collection of buttons in a jar'),
            ('still life', 'A bowl of oatmeal cookies'),
            ('still life', 'A set of scented candles'),
            ('still life', 'A bowl of roasted nuts'),
            ('still life', 'A basket of blueberries'),
            ('still life', 'A bowl of quinoa with vegetables'),
            ('still life', 'A set of tea cups'),
            ('still life', 'A bowl of pumpkin soup'),
            ('still life', 'A collection of vintage cameras'),
            ('still life', 'A bowl of French fries with ketchup'),
            ('still life', 'A basket of fresh croissants'),
            ('still life', 'A bowl of miso soup'),
            ('still life', 'A set of crystal glasses'),
            ('still life', 'A bowl of butternut squash soup'),
            ('still life', 'A basket of fresh baguettes'),
            ('still life', 'A bowl of pho with garnishes'),
            ('still life', 'A set of ceramic bowls'),
            ('nature', 'A single sunflower standing tall in a field'),
            ('nature', 'A winding path through a forest of tall trees'),
            ('nature', 'A close-up of a dewdrop on a leaf'),
            ('nature', 'A mountain range with snow-capped peaks'),
            ('nature', 'A serene lake surrounded by pine trees'),
            ('nature', 'A field of wildflowers in full bloom'),
            ('nature', 'A small waterfall cascading over rocks'),
            ('nature', 'A close-up of a blooming rose'),
            ('nature', 'A desert landscape with cacti and sand dunes'),
            ('nature', 'A seaside cliff with waves crashing below'),
            ('nature', 'A cherry blossom tree in full bloom'),
            ('nature', 'A meadow with butterflies and tall grass'),
            ('nature', 'A close-up of a spider web covered in morning dew'),
            ('nature', 'A river winding through a lush valley'),
            ('nature', 'A close-up of a fern frond unfurling'),
            ('nature', 'A peaceful beach with seashells scattered in the sand'),
            ('nature', 'A close-up of a cluster of vibrant tulips'),
            ('nature', 'A rolling hillside covered in golden autumn leaves'),
            ('nature', 'A grove of bamboo with sunlight filtering through'),
            ('nature', 'A quiet pond with lily pads and a frog'),
            ("building", "Cozy log cabin in the woods"),
            ("building", "Simple stone bridge over a stream"),
            ("building", "Traditional red barn with a weather vane"),
            ("building", "Rustic country farmhouse"),
            ("building", "Modern glass skyscraper"),
            ("building", "Quaint English cottage with a thatched roof"),
            ("building", "Lighthouse on a rocky coastline"),
            ("building", "Medieval castle with turrets"),
            ("building", "Row of colorful townhouses"),
            ("building", "Classic Victorian mansion"),
            ("building", "Small mountain chalet"),
            ("building", "Greek temple with columns"),
            ("building", "Japanese pagoda surrounded by cherry blossoms"),
            ("building", "Rustic wooden treehouse"),
            ("building", "Roman aqueduct"),
            ("building", "Traditional windmill in a field"),
            ("building", "Simple log cabin by a lake"),
            ("building", "Gothic cathedral with stained glass windows"),
            ("building", "Quaint little chapel in the countryside"),
            ("building", "Modern suburban house with a garden"),
            ("fantasy", "A dragon perched on a mountain peak"),
            ("fantasy", "A unicorn grazing in a mystical forest"),
            ("fantasy", "A fairy sitting on a mushroom"),
            ("fantasy", "A mermaid swimming in a crystal-clear lagoon"),
            ("fantasy", "A phoenix rising from its ashes"),
            ("fantasy", "A centaur galloping through a meadow"),
            ("fantasy", "A castle floating in the clouds"),
            ("fantasy", "An enchanted forest with glowing flowers"),
            ("fantasy", "A wizard casting a spell in his tower"),
            ("fantasy", "A griffin soaring over a medieval city"),
            ("fantasy", "A gnome working in a magical garden"),
            ("fantasy", "A troll guarding a stone bridge"),
            ("fantasy", "An elf archer in a dense woodland"),
            ("fantasy", "A sorceress summoning a storm"),
            ("fantasy", "A giant's footprint in a valley"),
            ("fantasy", "A haunted shipwreck under the sea"),
            ("fantasy", "A portal to another dimension"),
            ("fantasy", "A knight battling a giant serpent"),
            ("fantasy", "A celestial palace among the stars"),
            ("fantasy", "A woodland creature playing a magical flute"),
            ("people", "A child flying a kite in a park"),
            ("people", "A chef preparing a meal in the kitchen"),
            ("people", "A teacher reading to a group of children"),
            ("people", "A musician playing the guitar on a street corner"),
            ("people", "A gardener planting flowers in a garden"),
            ("people", "A couple dancing under the stars"),
            ("people", "A scientist working in a lab"),
            ("people", "A firefighter rescuing a cat from a tree"),
            ("people", "A painter creating a mural on a wall"),
            ("people", "A hiker reaching the top of a mountain"),
            ("people", "A fisherman casting a line into a lake"),
            ("people", "A nurse caring for a patient"),
            ("people", "A surfer riding a big wave"),
            ("people", "A ballet dancer performing on stage"),
            ("people", "A pilot flying an airplane"),
            ("people", "A librarian organizing books on a shelf"),
            ("people", "A runner finishing a marathon"),
            ("people", "A photographer taking pictures in a city"),
            ("people", "A construction worker building a house"),
            ("people", "A barista making coffee in a café"),
            ("people", "A reclining nude in soft lighting"),
            ("people", "A standing nude in a natural pose"),
            ("people", "A sitting nude on a draped fabric"),
            ("people", "A nude figure drawing with a focus on curves and shadows")

        ]

        for category, prompt_text in prompts:
            prompt = Prompt(
                text=prompt_text,
                category=category
            )
            db.session.add(prompt)
    
        db.session.commit()

if __name__ == '__main__':
    init_db()
